import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Forest actions + filter slab; lime is accent only
        primary: '#003F3B',
        'lime-brand': '#72D35F',
        'primary-container': '#72D35F',
        'primary-fixed': '#6bf8ee',
        'primary-fixed-dim': '#48dbd2',
        'on-primary': '#ffffff',
        'on-primary-container': '#00504c',
        'on-primary-fixed': '#00201e',
        'on-primary-fixed-variant': '#00504c',

        secondary: '#006c4b',
        'secondary-container': '#64f9bc',
        'secondary-fixed': '#68fcbf',
        'secondary-fixed-dim': '#45dfa4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714e',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',

        tertiary: '#55615f',
        'tertiary-container': '#abb8b5',
        'tertiary-fixed': '#d8e5e2',
        'tertiary-fixed-dim': '#bcc9c6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3d4947',
        'on-tertiary-fixed': '#121e1c',
        'on-tertiary-fixed-variant': '#3d4947',

        background: '#FFFFFF',
        'on-background': '#111111',

        surface: '#FFFFFF',
        'surface-bright': '#FFFFFF',
        'surface-card': '#F3F4F6',
        'surface-dim': '#cfdaf2',
        'surface-tint': '#003F3B',
        'surface-variant': '#d8e3fb',
        'surface-container': '#e7eeff',
        'surface-container-low': '#f0f3ff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#111111',
        'on-surface-variant': '#555555',

        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'inverse-primary': '#48dbd2',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        outline: '#6c7a78',
        'outline-variant': '#E5E7EB',
        'border-muted': '#bbcac7',

        'match-success': '#72D35F',
        'match-warning': '#45dfa4',
        'match-missing': '#e7eeff',
        'text-muted': '#888888',
        'success-green': '#2cc9c0',

        // Legacy aliases
        ink: '#111111',
        stone: '#3c4948',
        'off-white': '#f9f9ff',
        pearl: '#ffffff',
        'faded-stone': '#bbcac7',
        'shadow-tint': '#6c7a78',
        amber: '#006a65',
        'amber-hover': '#2cc9c0',
        'warning-red': '#ba1a1a',
        grape: '#d8e5e2',
        sunshine: '#6bf8ee',
        bg: '#f9f9ff',
        'surface-hover': '#f0f3ff',
        border: '#bbcac7',
        fg: '#111c2d',
        muted: '#6c7a78',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['Geist', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'stat-value': ['32px', { lineHeight: '1', fontWeight: '700' }],
        'data-lg': ['24px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.13', letterSpacing: '0.02em' }],
        'body-sm': ['14px', { lineHeight: '1.25' }],
        body: ['16px', { lineHeight: '1.5' }],
        subheading: ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-sm': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        heading: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      spacing: {
        section: '56px',
        'card-pad': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        'margin-mobile': '16px',
        'section-gap': '96px',
        'container-max': '1200px',
        sidebar: '260px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        card: '1rem',
        badge: '9999px',
        btn: '0.75rem',
        field: '0.75rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(17, 17, 17, 0.06), 0 10px 28px rgba(17, 17, 17, 0.08)',
        elevated: '0 6px 12px rgba(17, 17, 17, 0.08), 0 20px 44px rgba(17, 17, 17, 0.12)',
        glass: '0 0 40px rgba(0, 0, 0, 0.04)',
        'primary-glow': '0 8px 20px rgba(0, 63, 59, 0.25)',
      },
      maxWidth: {
        page: '1200px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0)' },
          '50%': { transform: 'scale(1.15)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'progress-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-up': 'slide-up 0.32s cubic-bezier(0.22, 1, 0.36, 1)',
        'scale-in': 'scale-in 0.3s ease-out',
        'shimmer': 'shimmer 1.5s linear infinite',
        'progress-pulse': 'progress-pulse 1.5s ease-in-out infinite',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
      },
      backgroundImage: {
        'shimmer-gradient': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.08) 50%, transparent 100%)',
      },
    },
  },
  plugins: [],
};

export default config;
