import type { RawJob } from '../types';
import { fetchRemotive } from './remotive';
import { fetchRemoteOk } from './remoteok';
import { fetchHackerNews } from './hackernews';
import { fetchArbeitnow } from './arbeitnow';
import { fetchAdzuna } from './adzuna';
import { fetchHimalayas } from './himalayas';
import { fetchJSearch } from './jsearch';
import type { SearchProfile } from '../search-profile';

export type SourceName =
  | 'remotive'
  | 'remoteok'
  | 'hn'
  | 'arbeitnow'
  | 'adzuna_in'
  | 'himalayas'
  | 'jsearch';

export const ALL_SOURCES: SourceName[] = [
  'remotive',
  'remoteok',
  'hn',
  'arbeitnow',
  'adzuna_in',
  'himalayas',
  'jsearch',
];

export const SOURCE_LABELS: Record<SourceName, string> = {
  remotive: 'Remotive',
  remoteok: 'RemoteOK',
  hn: 'HN Who is hiring',
  arbeitnow: 'Arbeitnow',
  adzuna_in: 'Adzuna India',
  himalayas: 'Himalayas',
  jsearch: 'JSearch',
};

/**
 * Build the dispatch table at call time.
 *
 * If a SearchProfile is provided, its AI-generated `searchKeywords` are used
 * for sources that support keyword search (e.g. Adzuna, JSearch, Himalayas).
 * The profile is generated by AI from the user's resume — this replaces the
 * previous regex-based query builder.
 */
function buildFns(searchProfile?: SearchProfile | null): Partial<
  Record<SourceName, () => Promise<RawJob[]>>
> {
  const fns: Partial<Record<SourceName, () => Promise<RawJob[]>>> = {
    remotive: () => fetchRemotive({ limit: 50 }),
    remoteok: () => fetchRemoteOk(),
    hn: () => fetchHackerNews({ limit: 60 }),
    arbeitnow: () => fetchArbeitnow(),
  };

  // Use AI-generated keywords from the search profile if available
  const queries = searchProfile?.searchKeywords?.length
    ? searchProfile.searchKeywords
    : [];

  // Adzuna India — enabled if credentials are configured
  // (supports either ADZUNA_CREDENTIALS or legacy ADZUNA_APP_ID + ADZUNA_APP_KEY)
  if (process.env.ADZUNA_CREDENTIALS || (process.env.ADZUNA_APP_ID && process.env.ADZUNA_APP_KEY)) {
    fns.adzuna_in = () =>
      fetchAdzuna({
        country: 'in',
        queries,
        maxPages: 2,
      });
  }

  // Himalayas — DISABLED: Their API ignores all filter params (query, category).
  // Returns a chronological dump of 100K+ jobs with no working search.
  // For niche domains like performance testing, <0.1% of results are relevant.
  // Re-enable if they fix their search endpoint.
  // fns.himalayas = () => fetchHimalayas({ limit: 100 });

  // JSearch (RapidAPI) — enabled if at least one API key is configured (env or DB)
  // Always register it — fetchJSearch will check keys at runtime and throw
  // a descriptive error if none exist. This way Admin Center keys work
  // without needing the env var.
  fns.jsearch = () =>
    fetchJSearch({
      queries: queries.length > 0 ? queries.slice(0, 5) : undefined,
      country: 'India',
      datePosted: 'week',
    });

  return fns;
}

export async function fetchAllSources(
  sources?: SourceName[],
  searchProfile?: SearchProfile | null,
): Promise<{ jobs: RawJob[]; errors: { source: string; error: string }[] }> {
  const errors: { source: string; error: string }[] = [];
  const all: RawJob[] = [];

  const fns = buildFns(searchProfile);
  const names = sources ?? (Object.keys(fns) as SourceName[]);

  await Promise.all(
    names.map(async (s) => {
      const fn = fns[s];
      if (!fn) {
        // Source not configured (e.g. missing API keys) — silently skip.
        return;
      }
      try {
        const jobs = await fn();
        all.push(...jobs);
      } catch (e) {
        errors.push({ source: s, error: (e as Error).message });
      }
    }),
  );

  return { jobs: all, errors };
}
