import type { RawJob } from '../types';
import { fetchRemotive } from './remotive';
import { fetchRemoteOk } from './remoteok';
import { fetchHackerNews } from './hackernews';
import { fetchArbeitnow } from './arbeitnow';
import { fetchAdzuna } from './adzuna';
import { fetchHimalayas } from './himalayas';
import { fetchJSearch } from './jsearch';
import { fetchLinkedIn } from './linkedin';
import type { SearchProfile } from '../search-profile';

export type SourceName =
  | 'remotive'
  | 'remoteok'
  | 'hn'
  | 'arbeitnow'
  | 'adzuna_in'
  | 'himalayas'
  | 'jsearch'
  | 'linkedin';

export const ALL_SOURCES: SourceName[] = [
  'remotive',
  'remoteok',
  'hn',
  'arbeitnow',
  'adzuna_in',
  'himalayas',
  'jsearch',
  'linkedin',
];

export const SOURCE_LABELS: Record<SourceName, string> = {
  remotive: 'Remotive',
  remoteok: 'RemoteOK',
  hn: 'HN Who is hiring',
  arbeitnow: 'Arbeitnow',
  adzuna_in: 'Adzuna India',
  himalayas: 'Himalayas',
  jsearch: 'JSearch',
  linkedin: 'LinkedIn',
};

/**
 * Build a high-coverage LinkedIn query set from the search profile.
 *
 * KEY INSIGHT: LinkedIn's keyword search matches ROLE-TITLE PHRASES far better
 * than niche tool names. e.g. searching "loadrunner" misses "Senior Lead -
 * Performance Engineering" at Levi Strauss, but "performance testing" and
 * "performance engineering" surface it. So we prioritise titlePatterns +
 * primaryDomain + adjacentDomains (role phrases), then add a few tool keywords.
 *
 * LinkedIn is free (no API token), so we can afford a broad query set.
 */
function buildLinkedInQueries(profile?: SearchProfile | null): string[] {
  if (!profile) return ['performance testing', 'performance engineer'];
  const out = new Set<string>();
  const add = (s?: string) => {
    const t = (s ?? '').trim().toLowerCase();
    if (t && t.length >= 3) out.add(t);
  };
  // Role-title phrases are the strongest signal on LinkedIn.
  (profile.titlePatterns ?? []).forEach(add);
  // Primary + adjacent domains (e.g. "performance engineering", "sre").
  add(profile.primaryDomain);
  (profile.adjacentDomains ?? []).forEach(add);
  // A few niche tool keywords for specialised coverage.
  (profile.searchKeywords ?? []).slice(0, 4).forEach(add);
  // Cap to keep request count + scan time bounded (LinkedIn is free but slow).
  return Array.from(out).slice(0, 10);
}

/**
 * Build the dispatch table at call time.
 *
 * If a SearchProfile is provided, its AI-generated `searchKeywords` are used
 * for sources that support keyword search (e.g. Adzuna, JSearch, Himalayas).
 * The profile is generated by AI from the user's resume — this replaces the
 * previous regex-based query builder.
 */
function buildFns(searchProfile?: SearchProfile | null): Partial<
  Record<SourceName, () => Promise<RawJob[]>>
> {
  const fns: Partial<Record<SourceName, () => Promise<RawJob[]>>> = {
    remotive: () => fetchRemotive({ limit: 50 }),
    remoteok: () => fetchRemoteOk(),
    hn: () => fetchHackerNews({ limit: 60 }),
    arbeitnow: () => fetchArbeitnow(),
  };

  // Use AI-generated keywords from the search profile if available
  const queries = searchProfile?.searchKeywords?.length
    ? searchProfile.searchKeywords
    : [];

  // Adzuna India — enabled if credentials are configured
  // (supports either ADZUNA_CREDENTIALS or legacy ADZUNA_APP_ID + ADZUNA_APP_KEY)
  if (process.env.ADZUNA_CREDENTIALS || (process.env.ADZUNA_APP_ID && process.env.ADZUNA_APP_KEY)) {
    fns.adzuna_in = () =>
      fetchAdzuna({
        country: 'in',
        queries,
        maxPages: 2,
      });
  }

  // Himalayas — always enabled (free, no auth)
  fns.himalayas = () =>
    fetchHimalayas({
      queries: queries.length > 0 ? queries.slice(0, 3) : undefined,
      limit: 50,
    });

  // JSearch (RapidAPI) — enabled if at least one API key is configured (env or DB)
  // Always register it — fetchJSearch will check keys at runtime and throw
  // a descriptive error if none exist. This way Admin Center keys work
  // without needing the env var.
  fns.jsearch = () =>
    fetchJSearch({
      queries: queries.length > 0 ? queries.slice(0, 5) : undefined,
      country: 'India',
      datePosted: 'week',
    });

  // LinkedIn — PUBLIC GUEST API (free, no auth, no API key).
  // Uses role-title phrase queries (best coverage on LinkedIn) built from the
  // full search profile, not just niche tool keywords. See buildLinkedInQueries.
  fns.linkedin = () =>
    fetchLinkedIn({
      queries: buildLinkedInQueries(searchProfile),
      location: 'India',
      maxPagesPerQuery: 4,
      fetchDescriptions: true,
      maxDescriptions: 60,
    });

  return fns;
}

export async function fetchAllSources(
  sources?: SourceName[],
  searchProfile?: SearchProfile | null,
): Promise<{ jobs: RawJob[]; errors: { source: string; error: string }[] }> {
  const errors: { source: string; error: string }[] = [];
  const all: RawJob[] = [];

  const fns = buildFns(searchProfile);
  const names = sources ?? (Object.keys(fns) as SourceName[]);

  await Promise.all(
    names.map(async (s) => {
      const fn = fns[s];
      if (!fn) {
        // Source not configured (e.g. missing API keys) — silently skip.
        return;
      }
      try {
        const jobs = await fn();
        all.push(...jobs);
      } catch (e) {
        errors.push({ source: s, error: (e as Error).message });
      }
    }),
  );

  return { jobs: all, errors };
}
