import type { Metadata } from 'next';
import { LegalDocumentLayout } from '@/app/_components/LegalDocumentLayout';
import {
  LEGAL_CONTACT_EMAIL,
  LEGAL_LAST_UPDATED,
  LEGAL_OPERATOR_NAME,
  PRODUCT_NAME,
} from '@/lib/legal/site';

export const metadata: Metadata = {
  title: 'Terms of Service',
  robots: 'noindex, follow',
};

export default function TermsPage() {
  return (
    <LegalDocumentLayout title="Terms of Service">
      <p className="text-sm text-stone mb-6">
        Last updated: {LEGAL_LAST_UPDATED}. By using {PRODUCT_NAME}, you agree to these terms.
      </p>

      <h2>1. The service</h2>
      <p>
        {PRODUCT_NAME} ({LEGAL_OPERATOR_NAME}) provides an AI-assisted job search tool: job
        aggregation, resume-based matching, scoring, and optional content generation. We are{' '}
        <strong>not</strong> an employer, recruiter, or placement agency. We do not guarantee
        interviews, offers, or hiring outcomes.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least <strong>18 years old</strong> and able to enter a binding contract. You
        must provide accurate account information and keep your login secure.
      </p>

      <h2>3. Your content</h2>
      <p>
        You retain ownership of your resume and other content you upload. By creating an account
        and accepting these Terms together with our Privacy Policy, you grant us a limited licence
        to store, process, and display your content to provide the service — including automated
        analysis and sending relevant portions to AI providers (as listed in the Privacy Policy)
        for job matching, scoring, and related suggestions.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>use the service for unlawful, fraudulent, or abusive purposes;</li>
        <li>upload malware or content you do not have rights to share;</li>
        <li>scrape, reverse-engineer, or overload our systems;</li>
        <li>misrepresent your identity or impersonate others;</li>
        <li>use the service in a way that violates third-party terms (job boards, employers, etc.).</li>
      </ul>

      <h2>5. Job listings & third parties</h2>
      <p>
        Job titles, descriptions, and links come from third-party sources. We do not verify every
        listing. When you apply on an external site, you are subject to that site&apos;s terms and
        privacy practices. {PRODUCT_NAME} is not responsible for third-party sites, employers, or
        the accuracy of listings.
      </p>

      <h2>6. AI-generated output</h2>
      <p>
        Scores, match reasons, resume edits, and cover letters are generated by automated systems
        and may contain errors. You are responsible for reviewing anything before you submit it to an
        employer.
      </p>

      <h2>7. Beta / availability</h2>
      <p>
        The service may change, break, or be unavailable without notice. Features may be added or
        removed during beta. We provide the service &quot;as is&quot; without warranties of
        uninterrupted or error-free operation.
      </p>

      <h2>8. Account termination</h2>
      <p>
        You may stop using {PRODUCT_NAME} at any time. We may suspend or terminate accounts that
        violate these terms or pose risk to the service or others. You may request account deletion
        via {LEGAL_CONTACT_EMAIL}.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by applicable law, {PRODUCT_NAME} and its operator are not
        liable for indirect, incidental, or consequential damages (including lost jobs, income, or
        data) arising from your use of the service. Our total liability for any claim related to the
        service is limited to the amount you paid us in the twelve months before the claim (or INR
        5,000 if you use a free tier).
      </p>

      <h2>10. Indemnity</h2>
      <p>
        You agree to indemnify us against claims arising from your misuse of the service or
        violation of these terms, to the extent permitted by law.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These terms are governed by the laws of <strong>India</strong>. Courts in India shall have
        jurisdiction, subject to mandatory consumer protection rules that may apply to you.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions: <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>
      </p>

      <p className="text-sm text-stone mt-8">
        This document is a practical starter for a small service and is not a substitute for advice
        from a qualified lawyer.
      </p>
    </LegalDocumentLayout>
  );
}
